{% set version = "2.9.1" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 1a2f66ffa66d3fa82cd1cdba3fe6e094562f9513f44a0f587ed7d51af413880b  # [linux64]

  fn: pandoc.pkg  # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: d57d68477b151bb610f80cda9a8256f8d235f0ac46c710afefcbd2210e256897  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 55d46cf42cdf50d80234c03a12e886c8f060ea9749d2ff6216e52ab8031f5a8b  # [win]

build:
   number: 0

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Universal markup converter (repackaged binaries)'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
