{% set version = "2.12" %}

package:
  name: pandoc
  version: {{ version }}  # [not ppc64le and not win32]
  version: "2.2.1"  # [ppc64le]
  version: "2.9.2.1"  # [win32]

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 6d89c16f31ef4cd826133b35bbe978dd2ca7328d7b8d51fbaf2c02ca5b5553e0  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: ec41752bcea7416d00e7f845d58351dc831246b910004cfe62d52079085a640a  # [aarch64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.zip  # [osx]
  sha256: 7a23d5ed5e4eab251c8c208a25330a53787eec8216e4b768f194f850a64dc664  # [osx]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.zip  # [win64]
  sha256: 3ed3283438a1a3d45b8c1fb3cddb87cf93c86064b84de4f8521436292ed94e50  # [win64]

  # upstream no longer provides win-32 binaries
  url: https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-windows-i386.zip    # [win32]
  sha256: 5a9818493f8b14821c5fb44234c898f776faf011089dc77e1dcf6ba3e51e0a81  # [win32]

  # repackage the RPM built for EPEL
  url: https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/epel-7-ppc64le/00770404-pandoc/pandoc-2.2.1-1.el7.ppc64le.rpm  # [ppc64le]
  sha256: 5a9818493f8b14821c5fb44234c898f776faf011089dc77e1dcf6ba3e51e0a81  # [ppc64le]

build:
  number: 0  # [ppc64le]
  number: 0  # [win32]
  number: 0  # [not ppc64le and not win32]
  binary_relocation: False  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

# The pandoc binary from the RPM depends on libgmp, libz and libffi and system libraries.
# Add these as host requirements to pick up the correct run_exports
{% if ARCH == "ppc64le" %}
requirements:
  build:
    - patchelf
    # we do not actually need a compiler but want the
    # sysroot for link checking and the run_exports
    # avoid {{ compiler('c') }} which adds unneeded hashes on all platforms
    - gcc_linux-ppc64le
  host:
    - gmp 6.1.2
    - zlib 1.2.11
    - libffi 3.3
{% endif %}

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter (repackaged binaries)
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/tree/master/doc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
