{% set version = "2.9.2.1" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 5b61a981bd2b7d48c1b4ba5788f1386631f97e2b46d0d1f1a08787091b4b0cf8  # [linux64]

  fn: pandoc.pkg  # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: 6f2ef40dcc0edf6646bc4ed0622c5c33dd82c82c303a35bd9166d9f10561fc94  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 9c9f5fbde483519bb4cc55df9ec54b537ce30593c45abdc7e7426a4ee5e229e4  # [win]

build:
  number: 0

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter (repackaged binaries)

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
