{% set name = "pandoc" %}
{% set version = "3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jgm/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-linux-amd64.tar.gz  # [linux and x86_64]
  sha256: 1a035c1f7d295c353f614461fa4bc13d703c0e865387d44341d1556d703de59a  # [linux and x86_64]
  url: https://github.com/jgm/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [linux and aarch64]
  sha256: 87cac7b2b02495c0533f75193b40837c50c5c313d905b19829c721d617a073b9  # [linux and aarch64]
  url: https://github.com/jgm/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-arm64-macOS.zip  # [osx and arm64]
  sha256: 7cfaa04a57816397dd6498fd50ada01bdeb04feefab737da37d493fb30131533  # [osx and arm64]
  url: https://github.com/jgm/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 3c72ee9966d2a35ebb59873967e496f5fe745c15cf9e825947dc745d19b36bad  # [win]

build:
  number: 0
  binary_relocation: false  # [osx]

# OSX dynamic section:
#/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.12)
#/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
#/usr/lib/libffi.dylib (compatibility version 1.0.0, current version 40.0.0)
#/usr/lib/libcharset.1.dylib (compatibility version 1.0.0, current version 1.0.0)
requirements:
  run:
    - zlib  # [osx]
    - libiconv  # [osx]
    - libffi >=3.4,<3.5

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: https://pandoc.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: https://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
    - katietz
  skip-lints:
    # binary repack
    - cbc_dep_in_run_missing_from_host
