{% set version = "1.18" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc-{{ version }}-amd64.deb                                                                     # [linux64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: c2216843dff1da7535055c6cf95cf35160ff7c698dae58a21b83a9c1d68df018                               # [linux64]
  fn: pandoc-{{ version }}.pkg                                                                           # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-osx.pkg        # [osx]
  sha256: 747ae7bfddeeed48d83c449559ceae8ecfc5cfa1fccdbab9f22a23c31913ae76                               # [osx]
  fn: pandoc-{{ version }}-windows.msi                                                                   # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: 30c308603a960c69a72710f0e56ba0e60e1556d76a83dc6034f52af89871ad8b                               # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
