{% set version = "1.19" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc-{{ version }}-amd64.deb                                                                     # [linux64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: 0b5b7bf22a6b93d21b468363148b3eab5363fb4570c43bb340d41f30c93f92c6                               # [linux64]
  fn: pandoc-{{ version }}.pkg                                                                           # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-osx.pkg        # [osx]
  sha256: 49b548d9bd85a93d881d38cbd663534702a064a1342b2edbb5a14acb73158521                               # [osx]
  fn: pandoc-{{ version }}-windows.msi                                                                   # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: deedb235e891d5736d0e9151c8d152fa76b311ba67db7407488a06bc5301132c                               # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
