{% set version = "2.7.3" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc.deb  # [linux]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb  # [linux64]
  sha256: 5dc29869782e67b4ca0a5b484d5f6c731b02240c2660c9a2792205937c8f2a89  # [linux64]

  fn: pandoc.pkg  # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: 040bd4b7eb1f586269c202de6bb212dbfe58123c389a1ecf8064ab02b0ef3b52  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 1d13e516868ac18dde5054296ce9acb935565d4d3d705c34f60c700eb70ba537  # [win]

build:
   number: 0

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Universal markup converter (repackaged binaries)'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
