{% set version = "1.19.1" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc-{{ version }}-amd64.deb                                                                     # [linux64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: cb31d29ee8a34aa2fed135c75dd99748ae814f3008d82b6cdb5fd35aec3e7c72                               # [linux64]
  fn: pandoc-{{ version }}.pkg                                                                           # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-osx.pkg        # [osx]
  sha256: 6b055e43d8b0d7f632150c3d82d02fc5ed6127f41e69471c79bde475e86e4f0b                               # [osx]
  fn: pandoc-{{ version }}-windows.msi                                                                   # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: 01965414eb03a66b9d49c334e7e635b90518005530f9c8d619c30200403b6a19                               # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
