{% set version = "2.3" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb  # [linux64]
  sha256: 77cc8aa981a333975f9167686feb201dff4123dcfc813dab5bcdfc5da4bb89f2  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: 2ed3aebf95e5f206639913736d2257d01f19bcf4289f1b4f8e7e1de9096673f7  # [osx]

  fn: pandoc-{{ version }}-windows-x86_64.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-windows-x86_64.msi  # [win]
  sha256: 11355b3bfb337fb1d9896a8dc4219ce44d2a0fbfc7b92820c879b7a1e68c3705  # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.11  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries)'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
