{% set version = "2.2.1" %}

package:
  name: pandoc
  version: {{ version }}  # [not linux32]
  version: 1.15.0.6       # [linux32]
  version: 2.0.0.1        # [ppc64le]

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb  # [linux64]
  sha256: 2a8c536721047c0512ad44d54da2908a937d604e1c29fcb948be3cb0cbe8842c  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: ad84eac40c1c93610e72eda00bc38b03d8fb2b515151c0439a61fcb3eaf45c95  # [osx]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: a95ba5f684f893b43e45d123ce4c70f48a31721b2db0536662943fb8332bdd2e  # [win]

  url: https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc-el5/epel-5-i386/00125413-pandoc/pandoc-1.15.0.6-1.i386.rpm  # [linux32]
  sha256: 4ed1d4a181366cf07f8a575cd7424f3f032daabd439c2e07c1da867ecf47d79e                                                         # [linux32]

  url: https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/fedora-27-ppc64le/00684534-pandoc/pandoc-2.0.0.1-1.fc27.ppc64le.rpm  # [ppc64le]
  sha256: ddcd2e07bbbabb546d62fa35b0ef4f9c84f788d434485e8af62708f646b1ad29                                                                  # [ppc64le]

build:
  number: 0
  # pandoc is a repacked binary, whitelist all DSOs
  missing_dso_whitelist:
    - '*'

requirements:
  run:
    - gmp     # [linux]
    - zlib    # [linux]
    - libffi  # [linux32 or ppc64le]
    - yaml    # [ppc64le]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/tree/master/doc

extra:
  recipe-maintainers:
    - jankatins
    - mingwandroid
    - ocefpaf
    - dhimmel
