{% set version = "2.0" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc-{{ version }}-amd64.deb                                                                     # [linux64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-3-amd64.deb    # [linux64]
  sha256: 381cde6bb2360bbcbf4ecac69eaec625f8858a8ee8cfa11b5d951e35c3fc92d9                               # [linux64]
  fn: pandoc-{{ version }}.pkg                                                                           # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg      # [osx]
  sha256: a35aeee1d57bb6aa0271b5701637d3afc04d1dfca9a0368c2ef4778711ba1a60                               # [osx]
  fn: pandoc-{{ version }}-windows.msi                                                                   # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: 30fd7386cdc3fe17f91c545626999bd121a2ec5d77a26b6988291af8012262fc                               # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
    - dhimmel
