{% set v = "1.17.0.1" %}

package:
  name: pandoc
  version: {{ v }}

source:
  fn:   pandoc-{{ v }}-amd64.deb                                                            # [linux64]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-1-amd64.deb  # [linux64]
  md5:  827e87a4188d0ac49095835a3bf0a3c6                                                    # [linux64]
  fn:   pandoc-{{ v }}.pkg                                                                  # [osx]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-osx.pkg      # [osx]
  md5:  1321e443caf6a5a7b52098ebc5151090                                                    # [osx]
  fn:   pandoc-{{ v }}-windows.msi                                                          # [win]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-windows.msi  # [win]
  md5:  ea2bb7f6c65012a865b33fe76f87e6f8                                                    # [win]

requirements:
  run:
    - gmp               # [linux64]
    - zlib              # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL
  summary: Universal markup converter (repackaged binaries)

extra:
  recipe-maintainers:
    - janschulz
