{% set v = "1.17.0.2" %}

package:
  name: pandoc
  version: {{ v }}

source:
  fn:   pandoc-{{ v }}-amd64.deb                                                            # [linux64]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-1-amd64.deb  # [linux64]
  md5:  66c19c0d0b4908385e0a9318359b8eb0                                                    # [linux64]
  fn:   pandoc-{{ v }}.pkg                                                                  # [osx]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-osx.pkg      # [osx]
  md5:  eddcd678bbb33b809755e62646ceee00                                                    # [osx]
  fn:   pandoc-{{ v }}-windows.msi                                                          # [win]
  url:  https://github.com/jgm/pandoc/releases/download/{{ v }}/pandoc-{{ v }}-windows.msi  # [win]
  md5:  5b81d93eb97e0f66bed4fe059ad7f67d                                                    # [win]

build:
    number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL
  summary: Universal markup converter (repackaged binaries)

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
