travis:
  secure:
    BINSTAR_TOKEN: sraaoVYbP6c3mOgLkEZUByxMG8HQ9lr/h32bzLOBggZTtA1kfQS5OW7N3CdUQtk8Z3OBJQLxI1BpuB8oUPxmcR+2SHkK2O7a5TVr14MMK+bvOGXAfPpNbfffTL0aDM84VQ8AGtNBLxeYSsJOz6oSA96ql8UmVmxI6pQZ4Z1d/m4pIHbxr0/Msnq+W08fd1skyb0nfl07rdX6udK352EGqvcGDZfpQy4q0qFu4uGJi8S4XdklKlsAvhc6uPzbOIbMzQ1kZkw69pMOVt3ffgf0p2j6SIFVG1E9xVMRdYodLXuoB4WGxBIpyOhMO4/lKs/bY5Movvozo8ngznt5lGClPOEDvG1Qdt6szy1vlDauhyRr6F7Tq5ry5LB39dUsv7sJqvPwQdqAD6/P6B08ScISOWTwrYv0BK7NUJdr0a6HFrBpPdyC3OdHIvJeSGNNTA3vrVumrLR4ermVrLIwYnr19FLgNtxkmxEssI/A72DrrXnSvk7movzANfm7fMQBeqNWB0v68e8Dm++UWZoLXnEMMTVC5qph0eJk9qTNSYktus+GCyuRxuk2lp1wRjmvR7KgBf0EYgyAGmNozHSwGbS8nZf0HC2gPtE/GfMkfkawQC2SuLI5jQivt8U65aLzPfP5ptfMGWoqx9NCmjRIhDYK8JOrMr6bYNvr+4VT57PLkpE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
